# Generated by Django 5.1.7 on 2025-04-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
