# Generated by Django 5.1.7 on 2025-07-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_gift_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('red', 'Rojo'), ('azul', 'Azul'), ('green', 'Verde'), ('orange', 'Naranja'), ('purple', 'Morado')], default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('birthday', 'Cumpleaños'), ('wedding', 'Matrimonio'), ('anniversary', 'Aniversario'), ('other', 'Otro')], default='birthday', max_length=20),
        ),
        migrations.AlterField(
            model_name='gift',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'Alto'), ('medium', 'Mediano'), ('low', 'Bajo')], max_length=10, null=True),
        ),
    ]
