# Generated by Django 5.1.7 on 2025-07-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_event_color_alter_event_type_alter_gift_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('green', 'Verde'), ('orange', 'Naranja'), ('purple', 'Morado')], default='red', max_length=20),
        ),
    ]
