# Generated by Django 5.2.4 on 2025-07-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('CUMPLEAÑOS', 'Cumpleaños'), ('BODA', 'Boda'), ('BABY_SHOWER', 'Baby Shower'), ('NAVIDAD', 'Navidad'), ('OTRO', 'Otro')], max_length=20)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
