# Generated by Django 5.2.1 on 2025-06-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregistry', '0001_initial'),
    ]

    def insertData(self, schema_editor):
        Group = self.get_model('auth', 'Group')


        administrador = Group(name='Administrador')
        administrador.save()
        cliente = Group(name='Comprador')
        cliente.save()


    operations = [
        migrations.RunPython(insertData, atomic=True)
    ]
