# Generated by Django 5.2.1 on 2025-06-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregistry', '0002_add_roles'),
    ]

    def insertData(self, schema_editor):
        Group = self.get_model('auth', 'Group')
        Permission = self.get_model('auth', 'Permission')

        admin_group = Group.objects.get(name='Administrador')
        comprador_group = Group.objects.get(name='Comprador')

        user_view = Permission.objects.get(codename='view_user')
        user_create = Permission.objects.get(codename='add_user')
        user_update = Permission.objects.get(codename='change_user')
        user_delete = Permission.objects.get(codename='delete_user')
        comprador_group.permissions.set([
        ])
        admin_group.permissions.set([
            user_view,
            user_create,
            user_update,
            user_delete,
        ])

    operations = [
        migrations.RunPython(insertData, atomic=True)
    ]